
spring:
  datasource:
    url: jdbc:h2:file:./auth_db;AUTO_SERVER=TRUE;NON_KEYWORDS=USER;
    username: auth
    password: auth
    driver-class-name: org.h2.Driver
  application:
    name: api-service
  sql:
    init:
      mode: always
      platform: h2

secret:
  access-token:
    key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4NDQyNDY1MywiaWF0IjoxNjg0NDI0NjUzfQ.ww43ej4kliluWb9eQS_D3ymn3Abzlx1BhurlpncBfQM
  refresh-token:
    key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY4NDQyNDY1MywiaWF0IjoxNjg0NDI0NjUzfQ.ww43ej4kliluWb9eQS_D3ymn3Abzlx1BhurlpncBfQM